version: "3.8"

services:
  data_recoder:
    build:
      context: .
      ssh:
        - default
    container_name: data_recoder
    image: data_recoder
    network_mode: host
    volumes:
      - ./volume_lib/net-ft-ros:/home/ros_ws/src/net-ft-ros
      - ./volume_lib/vrpn_client_ros:/home/ros_ws/src/vrpn_client_ros
      - ./volume_lib/ros_myo:/home/ros_ws/src/ros_myo
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    privileged: true
    devices:
      - /dev:/dev
      - /dev/ttyACM0:/dev/ttyACM0
    # command: bash
    tty: true     # <-- Add this line to keep bash open
    stdin_open: true # <-- Add this line